theme: jekyll-theme-cayman
title: Welcome to Kyle Tupper's homepage!
description: This repository has some of my work, feel free to check it out!
**I am currently a Computer Science student at Boise State University**
My favorite NBA team: https://www.nba.com/warriors/
