theme: jekyll-theme-cayman
title: Welcome to Kyle Tupper's homepage!
description: This repository has some of my work, feel free to check it out!
Mark Twain once said:
>Twenty years from now you will be more disappointed 
>by the things that you didn’t do than 
>by the ones you did do.”
My favorite NBA team: https://www.nba.com/warriors/
